#!/usr/bin/env bash
# a bash that transfers a file from our client to a server

# Check for the correct number of parameters
if [ "$#" -lt 4 ];
then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    FILE_PATH=$1
    SERVER_IP=$2
    USERNAME=$3
    SSH_KEY_PATH=$4
# Transfer the file using scp with strict host key checking disabled
    scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP":~
fi
