#!/usr/bin/env bash
#installing ngnix with the required parameters

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx Full'
echo "Hello World!" > /tmp/tempfile.txt
sudo mv /tmp/tempfile.txt /var/www/html/index.nginx-debian.html
sudo service nginx start
