#!/usr/bin/env bash
#installing ngnix with the required parameters

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx Full'
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx restart